# Generated by Django 5.0.1 on 2024-02-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='name',
        ),
    ]
